### PR TITLE
Added javascript solution to this program which was explained only logically before

### PR DESCRIPTION
**Pull request by kapilraghuwanshi**

### CODE REVIEW

**Comment by kapilraghuwanshi** [comment]
@profnandaa @asaph @targunp   Can anyone from Authors or (one who has write access of repo), please merge my pull requests?

**Review by profnandaa — COMMENTED** [review]
How memory efficient is this, what will be the Big-O?

**Comment by kapilraghuwanshi** [comment]
> How memory efficient is this, what will be the Big-O?

Time Complexity - O(n)
Space Complexity - O(n)

**Review by profnandaa — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
